### ISSUE TITLE
Prefer `Void` over `()` for return types of closures?

### ISSUE THREAD

**Issue by neilpa** [github/swift-style-guide#39]
Wanted to bring this up here after looking at ReactiveCocoa/ReactiveCocoa#2059. Personally I prefer `()` but it's probably better to be consistent with Apple.

* https://devforums.apple.com/message/1133616#1133616
* http://ericasadun.com/2015/05/11/swift-vs-void/

I can open a PR if there's consensus

**Comment by mdiep** [comment]
Consistency with Apple on this seems worthwhile to me. But I don't have strong feelings.

**Comment by alanjrogers** [comment]
I much prefer `()` too. Apple have been wrong with their standards plenty of times in the past. :trollface:

**Comment by alskipp** [comment]
For what it's worth, my vote is certainly for `()`. I fail to see the value of `Void` as an alternative, it obscures more than it clarifies.

**Comment by robrix** [comment]
`Void` is a `typealias`, so the debugger (for example) is always going to print `()` instead. I suggest `()`.

That said, I’m not sure this actually warrants an entry in the style guide. I think the document is at its best when it’s encouraging best practices for the project and/or the team, and I’m not sure that `()` vs. `Void` really matters.

**Comment by MarcoSero** [comment]
Just my 2 cents: whatever the final decision will be, I think this should be in the style guide to enforce consistency.

**Comment by robrix** [comment]
> I think this should be in the style guide to enforce consistency.

Consistency for consistency’s sake isn’t really in this guide’s charter. “Fewer debates about aesthetics” is the last item on the list for good reason, and since we haven’t had a debate about this on our team, there’s little to be gained by adding it here.

That said, if a team finds this guide useful but has some key differences, they should feel free to fork it & add whatever they see fit—this is, after all, only one team’s style guide, and thus not necessarily representative of any other team’s needs.

Or otherwise put: I don’t believe that there’s a one size fits all solution to code style, and I’d prefer not to act too speculatively—after all, who knows what the language will look like a week from now? :smile:

**Comment by robrix** [comment]
I’m going to close this out since there isn’t much to motivate a style guide rule.

**Comment by neilpa** [comment]
:+1:  Thanks for the discussion.
